version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: symfony/phpunit-bridge
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.6
  - dependency-name: twig/extra-bundle
    versions:
    - 3.2.1
    - 3.3.0
  - dependency-name: twig/twig
    versions:
    - 3.2.1
    - 3.3.0
  - dependency-name: symfony/orm-pack
    versions:
    - 2.1.0
  - dependency-name: symfony/asset
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/serializer
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/browser-kit
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/twig-bundle
    versions:
    - 5.2.2
    - 5.2.3
