language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

branches:
  only:
    - master

matrix:
  include:
    - php: 7.4

before_install:
  - composer require satooshi/php-coveralls

install:
  - composer install

script:
  - php bin/phpunit --coverage-clover ./tests/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
